### ISSUE TITLE
Sleep and USB

### ISSUE THREAD

**Issue by everybodies** [felipefrizzo/opencore-asus-strix-z490#1]
hey there,

thanks for posting this setup, it helped me with a Strix z490-h.  works just fine with a little massage.
i dont understand how you've achieved wake and sleep with USBinjectall.kext and no USB mapping.
do you mind to explain?

regars,
Marty

**Comment by felipefrizzo** [comment]
The wake and sleep worked out of the box, I didn't need to do anything

**Comment by lurepheonix** [comment]
@everybodies if your hackintosh doesn't sleep for some reason and you have Transmission installed && running, check its settings. You'll be pretty amazed.
Spend a considerable amount of time trying to figure it out, now I wanna look at the face of the guy who thought of inventing an option "Prevent computer from sleeping with ACTIVE transfers" (already downloaded and now uploading included, of course) and enabling it by default (!!!).

**Comment by everybodies** [comment]
hey guys,
thanks for reply. i can never achieve sleep without USB mapping. but thats possibly because i use bcm94360cd for wifi and bluetooth.
@lurepheonix thanks, i have that setting in Utorrent on mojave plex server.  this command is the bomb:
pmset -g assertions
it will tell you what's keeping the Mac awake.

**Comment by lurepheonix** [comment]
> i can never achieve sleep without USB mapping. but thats possibly because i use bcm94360cd for wifi and bluetooth.

Probably this is the core of the problem.
> pmset -g assertions

The most "amazing" thing about Transmission is that it doesn't show up there, or in Activity monitor, as an app that is preventing sleep.

**Comment by everybodies** [comment]
ha ha. really? 
ok. thanks for heads up. 
i use Utorrent because it can use a proxy.  Tranmission can not. Folx on Big Sur

i wouldn't call bcm94360 a problem. have two of them. paid about $80 each.
yea, usb bluetooth works just fine, but these work as soon as you power on and also between MacOS distros as well as in Windows without any fuss.
